---
#Configuring LAMP
- name: "Redhat Install"
  yum:
    name: 
      - httpd
      - mariadb-server
      - MySQL-python
      - php
      - php-mysql
    state: present

- name: "Starting mariadb"
  service:
    name: mariadb
    state: restarted

- name: "Copying config file"  
  template:
    src: httpd.tmp
    dest: /etc/httpd/conf/httpd.conf
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"

- name: "Virtualhost entry"
  template:
    src: virtual_host.tmp
    dest: /etc/httpd/conf.d/{{httpd_domain}}.conf
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
  notify:
    - redhat-apache

#Configuring Wordpress  
- name: "Creating document root"
  file:
    path: /var/www/html/{{httpd_domain}}
    state: directory
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"

- name: "Wordpress - Downloading Archive file"
  get_url:
    url: "{{ wordpress }}"
    dest: /tmp/wordpress.tar.gz

- name: "Extracting tar file"
  unarchive:
    remote_src: true
    src: /tmp/wordpress.tar.gz
    dest: /tmp/

- name: "Copying website content"
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/{{httpd_domain}}/
    remote_src: true
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"

- name: "Copying wordpress config"
  template:
    src: wp-config.tmp
    dest: /var/www/html/{{httpd_domain}}/wp-config.php
  notify:
    - redhat-apache

#Configuring MySQL
- name: "Resetting Root password"
  ignore_errors: true
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: "{{mysql_password}}"
    host_all: true

- name: "Removing anonyous users"
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: "{{mysql_password}}"
    name: ''
    state: absent
    host_all: true

- name: "Created database Wordpress"
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{mysql_user}}"
    login_password: "{{ mysql_password }}"

- name: "Creating mysql user"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: localhost
    state: present
    priv: "{{ db_name }}.*:ALL"
    login_user: "{{mysql_user}}"
    login_password: "{{ mysql_password }}"