---
#Configuring LAMP
- name: "Ubuntu apache"
  apt:
    name: 
      - apache2
      - mysql-server
      - python3-mysqldb
      - php
      - php-mysql
    state: present

#Configuring Apache
- name: "Virtualhost entry"
  template:
    src: virtual_host.tmp
    dest: /etc/apache2/sites-enabled/{{httpd_domain}}.conf
  notify:
    - ubuntu-apache

#Configuring Wordpress
- name: "Creating document root"
  file:
    path: "/var/www/html/{{httpd_domain}}"
    state: directory
    owner: "{{apache_owner}}"
    group: "{{apache_group}}"

- name: "Wordpress - Downloading Archive file"
  get_url:
    url: "{{ wordpress }}"
    dest: /tmp/wordpress.tar.gz

- name: "Extracting tar file"
  unarchive:
    remote_src: true
    src: /tmp/wordpress.tar.gz
    dest: /tmp/

- name: "Copying website files"
  copy:
    src: /tmp/wordpress/
    dest: "/var/www/html/{{httpd_domain}}/"
    remote_src: true
    owner: "{{apache_owner}}"
    group: "{{apache_group}}"

- name: "Copying wordpress config"
  template:
    src: wp-config.tmp
    dest: /var/www/html/{{httpd_domain}}/wp-config.php
  notify:
    - ubuntu-apache

#Configuring MySQL
- name: "Resetting Root password"
  ignore_errors: true
  mysql_user:
    login_user: 'root'
    login_password: ""
    name: 'root'
    password: "{{mysql_password}}"
    host_all: true

- name: "Removing anonymous users"
  mysql_user:
    login_user: 'root'
    login_password: "{{mysql_password}}"
    name: ""
    state: absent
    host_all: true

- name: "Created database Wordpress"
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{mysql_user}}"
    login_password: "{{ mysql_password }}"

- name: "Creating mysql user"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: localhost
    state: present
    priv: "{{ db_name }}.*:ALL"
    login_user: "{{mysql_user}}"
    login_password: "{{ mysql_password }}"