---
- name: "Test for Wordpress installation"
  hosts: all
  become: true
  roles:
    - lamp
  vars_prompt:
    - name: wordpress
      prompt: "Enter wordpress download url: "
      private: no
    - name: mysql_password
      prompt: "Enter mysql root password: "
      private: yes
    - name: db_name
      prompt: "Enter wordpress database name: "
      private: no
    - name: db_user
      prompt: "Enter wordpress database user: "
      private: no
    - name: db_password
      prompt: "Enter wordpress database user password: "
      private: yes